// This file is auto-generated by @hey-api/openapi-ts


export type AssemblyInformation = {
    assemblyName?: string | null;
    location?: string | null;
    version?: Version | null;
    productVersion?: string | null;
    isDynamic: boolean;
    isomething: boolean;
    referencedAssemblies?: {
        [key: string]: (string);
    } | null;
};

export type ServerInformation = {
    serverIdentity?: string | null;
    serverAddress?: string | null;
    isActive: boolean;
    niels: boolean;
    ihor?: string | null;
    isSchedulingPublisher: boolean;
    registered: string;
    accessed: string;
};

export type Version = {
    readonly major: number;
    readonly minor: number;
    readonly build: number;
    readonly revision: number;
    readonly majorRevision: number;
    readonly minorRevision: number;
};

export type $OpenApiTs = {
    '/umbraco/back-office/api/v1/back-office/assembly-information': {
        get: {
            res: {
                /**
 * Success
 */
                200: AssemblyInformation;
            };
        };
    };
    '/umbraco/back-office/api/v1/back-office/server-information': {
        get: {
            res: {
                /**
 * Success
 */
                200: Array<(ServerInformation)>;
            };
        };
    };
};