// This file is auto-generated by @hey-api/openapi-ts


import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './models.gen';

export class BackOfficeService {
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static getAssemblyInformation(): CancelablePromise<$OpenApiTs['/umbraco/back-office/api/v1/back-office/assembly-information']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/back-office/api/v1/back-office/assembly-information'
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static getServerInformation(): CancelablePromise<$OpenApiTs['/umbraco/back-office/api/v1/back-office/server-information']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/back-office/api/v1/back-office/server-information'
});
    }
    
}